[tool.towncrier]
    package = "towncrier"
    filename = "CHANGELOG.md"
    underlines = ["-", "", ""]
    template = "towncrier/template.md"
    title_format = "v{version} - {project_date}"
    issue_format = "[#{issue}](https://github.com/okmehl/mehl/issues/{issue})"
    start_string = "<!-- TOWNCRIER -->"
